using System.Linq;
using System.Numerics;
using Content.Shared._Rat.Poker;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client._Rat.Poker;

[GenerateTypedNameReferences]
public sealed partial class PokerTableWindow : DefaultWindow
{
    public event Action? OnJoin;
    public event Action? OnLeave;
    public event Action? OnFold;
    public event Action? OnCheck;
    public event Action? OnCall;
    public event Action<int>? OnBet;
    public event Action<int>? OnRaise;
    public event Action? OnStartGame;

    private PokerTableBoundUserInterfaceState? _lastState;
    private RSI? _cardRsi;

    private const string CardRsiPath = "/Textures/EstacaoPirata/Objects/Misc/cards.rsi";
    private const string CardBackState = "singlecard_down_nanotrasen";

    // Card sizes  (RSI is 32x32 — scale 3x / 2x)
    private static readonly Vector2 BigCard = new(96, 96);
    private static readonly Vector2 SmallCard = new(64, 64);

    // Drag state for hole cards
    private int _dragIndex = -1;
    private readonly List<PokerCard> _myCardOrder = new();

    public PokerTableWindow()
    {
        RobustXamlLoader.Load(this);

        JoinButton.OnPressed += _ => OnJoin?.Invoke();
        LeaveButton.OnPressed += _ => OnLeave?.Invoke();
        StartButton.OnPressed += _ => OnStartGame?.Invoke();
        FoldButton.OnPressed += _ => OnFold?.Invoke();
        CheckButton.OnPressed += _ => OnCheck?.Invoke();
        CallButton.OnPressed += _ => OnCall?.Invoke();

        BetRaiseButton.OnPressed += _ =>
        {
            var amount = BetAmountSpinBox.Value;
            if (_lastState != null && _lastState.CurrentBet == 0)
                OnBet?.Invoke(amount);
            else
                OnRaise?.Invoke(amount);
        };

        BetSlider.OnValueChanged += args =>
        {
            var rounded = (int)Math.Round(args.Value);
            if (BetAmountSpinBox.Value != rounded)
                BetAmountSpinBox.OverrideValue(rounded);
        };

        BetAmountSpinBox.ValueChanged += args =>
        {
            if (Math.Abs(BetSlider.Value - args.Value) > 0.5f)
                BetSlider.Value = args.Value;
        };

        WinnerPanel.Visible = false;

        // Localize buttons and labels
        var loc = IoCManager.Resolve<ILocalizationManager>();
        JoinButton.Text = loc.GetString("poker-btn-join");
        LeaveButton.Text = loc.GetString("poker-btn-leave");
        StartButton.Text = loc.GetString("poker-btn-start");
        FoldButton.Text = loc.GetString("poker-btn-fold");
        CheckButton.Text = loc.GetString("poker-btn-check");
        BetRaiseButton.Text = loc.GetString("poker-btn-bet");
        CommunityLabel.Text = loc.GetString("poker-label-community");
        HandLabel.Text = loc.GetString("poker-label-your-hand");

        // Style the felt and panels
        TableFelt.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(0.10f, 0.30f, 0.16f, 1f),
            BorderThickness = new Thickness(2),
            BorderColor = new Color(0.05f, 0.18f, 0.08f)
        };
        HandPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(0.11f, 0.17f, 0.11f, 1f),
            BorderThickness = new Thickness(1),
            BorderColor = new Color(0.17f, 0.30f, 0.17f)
        };

        try
        {
            var rsc = IoCManager.Resolve<IResourceCache>();
            _cardRsi = rsc.GetResource<RSIResource>(new Robust.Shared.Utility.ResPath(CardRsiPath)).RSI;
        }
        catch { }
    }

    public void UpdateState(PokerTableBoundUserInterfaceState state)
    {
        _lastState = state;

        var loc = IoCManager.Resolve<ILocalizationManager>();
        PotLabel.Text = $"  |  {loc.GetString("poker-pot", ("amount", state.Pot))}";
        MyStackLabel.Text = $"  |  {loc.GetString("poker-stack", ("amount", state.MyStack))}";
        MyBetLabel.Text = $"  |  {loc.GetString("poker-bet", ("amount", state.MyBet))}";
        PhaseLabel.Text = loc.GetString($"poker-phase-{state.Phase.ToString().ToLower()}");

        var callAmount = state.CurrentBet - state.MyBet;
        CallButton.Text = callAmount > 0
            ? loc.GetString("poker-btn-call", ("amount", callAmount))
            : loc.GetString("poker-btn-check");

        var sliderMin = state.MinRaise;
        var sliderMax = Math.Max(state.MyStack, state.MinRaise);
        BetSlider.MinValue = sliderMin;
        BetSlider.MaxValue = sliderMax;
        BetAmountSpinBox.IsValid = v => v >= sliderMin && v <= sliderMax;
        if (BetAmountSpinBox.Value < state.MinRaise)
            BetAmountSpinBox.Value = state.MinRaise;

        BetRaiseButton.Text = state.CurrentBet == 0
            ? loc.GetString("poker-btn-bet")
            : loc.GetString("poker-btn-raise");

        var inGame = state.Phase != PokerRoundPhase.Waiting;
        var isMyTurn = state.IsMyTurn && inGame;
        var seated = state.MySeatIndex >= 0;

        JoinButton.Visible = !seated;
        LeaveButton.Visible = seated;
        StartButton.Visible = !inGame && seated;
        FoldButton.Visible = isMyTurn;
        CheckButton.Visible = isMyTurn && callAmount == 0;
        CallButton.Visible = isMyTurn && callAmount > 0;
        BetRaiseButton.Visible = isMyTurn;
        BetSlider.Visible = isMyTurn;
        BetAmountSpinBox.Visible = isMyTurn;

        // Community cards — 5 large slots
        CommunityCardsContainer.RemoveAllChildren();
        for (var i = 0; i < 5; i++)
        {
            var cardControl = i < state.CommunityCards.Count
                ? MakeCardRect(state.CommunityCards[i].GetSpriteName(), BigCard)
                : MakeCardBackRect(BigCard);
            CommunityCardsContainer.AddChild(cardControl);
        }

        // My hole cards — large, draggable
        MyCardsContainer.RemoveAllChildren();
        if (seated)
        {
            var me = state.Players.FirstOrDefault(p => p.SeatIndex == state.MySeatIndex);
            var holeCards = me?.HoleCards;
            if (holeCards != null && holeCards.Count > 0)
            {
                // Sync drag order
                if (_myCardOrder.Count != holeCards.Count)
                {
                    _myCardOrder.Clear();
                    _myCardOrder.AddRange(holeCards);
                }
                for (var i = 0; i < _myCardOrder.Count; i++)
                {
                    var idx = i;
                    var card = _myCardOrder[i];
                    var ctrl = MakeDraggableCard(card, idx);
                    MyCardsContainer.AddChild(ctrl);
                }
            }
            else
            {
                MyCardsContainer.AddChild(MakeCardBackRect(BigCard));
                MyCardsContainer.AddChild(MakeCardBackRect(BigCard));
            }
        }

        // Seat panels
        var seatContainers = new[]
        {
            Seat0Container, Seat1Container, Seat2Container,
            Seat3Container, Seat4Container, Seat5Container
        };
        foreach (var seat in seatContainers)
            seat.RemoveAllChildren();

        foreach (var player in state.Players)
        {
            if (player.SeatIndex < 0 || player.SeatIndex >= seatContainers.Length)
                continue;
            BuildPlayerSeatUI(seatContainers[player.SeatIndex], player, state.Phase);
        }

        // Winner banner
        if (!string.IsNullOrEmpty(state.WinnerName))
        {
            WinnerPanel.Visible = true;
            WinnerLabel.Text = loc.GetString("poker-winner", ("name", state.WinnerName));
            WinningHandLabel.Text = state.WinningHand != null
                ? loc.GetString($"poker-hand-{state.WinningHand.ToLower().Replace(" ", "")}")
                : string.Empty;
        }
        else
        {
            WinnerPanel.Visible = false;
        }
    }

    private void BuildPlayerSeatUI(BoxContainer container, PokerPlayerState player, PokerRoundPhase phase)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(2)
        };
        panel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = player.IsCurrentTurn
                ? new Color(0.25f, 0.25f, 0.08f, 0.9f)
                : new Color(0.12f, 0.12f, 0.14f, 0.9f),
            BorderThickness = new Thickness(player.IsCurrentTurn ? 2 : 1),
            BorderColor = player.IsCurrentTurn ? Color.Yellow : new Color(0.3f, 0.3f, 0.35f)
        };

        var inner = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(4, 3)
        };

        var nameColor = player.Status switch
        {
            PokerPlayerStatus.Folded => Color.Gray,
            PokerPlayerStatus.Winner => Color.Gold,
            _ when player.IsCurrentTurn => Color.Yellow,
            _ => Color.White
        };

        inner.AddChild(new Label
        {
            Text = player.PlayerName,
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = nameColor,
            Margin = new Thickness(0, 0, 0, 1)
        });

        if (player.Status != PokerPlayerStatus.Active || player.IsCurrentTurn)
        {
            inner.AddChild(new Label
            {
                Text = player.IsCurrentTurn ? "▶ Turn" : player.Status.ToString(),
                HorizontalAlignment = HAlignment.Center,
                FontColorOverride = player.IsCurrentTurn ? Color.Yellow : Color.Gray,
                Margin = new Thickness(0, 0, 0, 2)
            });
        }

        inner.AddChild(new Label
        {
            Text = $"{player.Stack} cr",
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = new Color(0.8f, 1f, 0.8f)
        });

        if (player.CurrentBet > 0)
        {
            inner.AddChild(new Label
            {
                Text = $"Bet: {player.CurrentBet} cr",
                HorizontalAlignment = HAlignment.Center,
                FontColorOverride = new Color(1f, 0.85f, 0.5f)
            });
        }

        // Cards for other players (small card backs or revealed at showdown)
        var cardsRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalAlignment = HAlignment.Center,
            SeparationOverride = 3,
            Margin = new Thickness(0, 3, 0, 0)
        };

        if (player.HoleCards != null && player.HoleCards.Count > 0)
        {
            foreach (var card in player.HoleCards)
                cardsRow.AddChild(MakeCardRect(card.GetSpriteName(), SmallCard));
        }
        else if (phase != PokerRoundPhase.Waiting && player.Status == PokerPlayerStatus.Active)
        {
            cardsRow.AddChild(MakeCardBackRect(SmallCard));
            cardsRow.AddChild(MakeCardBackRect(SmallCard));
        }

        inner.AddChild(cardsRow);
        panel.AddChild(inner);
        container.AddChild(panel);
    }

    // Creates a scaled TextureRect for a named RSI state
    private TextureRect MakeCardRect(string stateName, Vector2 size)
    {
        Texture? tex = null;
        if (_cardRsi != null && _cardRsi.TryGetState(stateName, out var st))
            tex = st.Frame0;

        return new TextureRect
        {
            Texture = tex,
            MinSize = size,
            SetSize = size,
            Stretch = TextureRect.StretchMode.Scale,
            Margin = new Thickness(2)
        };
    }

    private TextureRect MakeCardBackRect(Vector2 size)
        => MakeCardRect(CardBackState, size);

    // Draggable wrapper for a hole card
    private Control MakeDraggableCard(PokerCard card, int index)
    {
        var tex = MakeCardRect(card.GetSpriteName(), BigCard);

        var wrapper = new PanelContainer
        {
            MouseFilter = Control.MouseFilterMode.Stop,
            Margin = new Thickness(3),
            ToolTip = card.ToString()
        };
        wrapper.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(0.15f, 0.15f, 0.18f, 0.0f),
            BorderThickness = new Thickness(1),
            BorderColor = new Color(0.5f, 0.5f, 0.5f, 0.5f)
        };
        wrapper.AddChild(tex);

        wrapper.OnMouseEntered += _ =>
        {
            wrapper.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = new Color(1f, 1f, 1f, 0.08f),
                BorderThickness = new Thickness(2),
                BorderColor = Color.White
            };
        };
        wrapper.OnMouseExited += _ =>
        {
            wrapper.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = new Color(0f, 0f, 0f, 0f),
                BorderThickness = new Thickness(1),
                BorderColor = new Color(0.5f, 0.5f, 0.5f, 0.5f)
            };
        };

        // Swap cards on click (simple reorder)
        wrapper.OnKeyBindDown += args =>
        {
            _dragIndex = index;
        };
        wrapper.OnKeyBindUp += args =>
        {
            if (_dragIndex != index && _dragIndex >= 0 && _dragIndex < _myCardOrder.Count && index < _myCardOrder.Count)
            {
                (_myCardOrder[_dragIndex], _myCardOrder[index]) = (_myCardOrder[index], _myCardOrder[_dragIndex]);
                RefreshMyCards();
            }
            _dragIndex = -1;
        };

        return wrapper;
    }

    private void RefreshMyCards()
    {
        MyCardsContainer.RemoveAllChildren();
        for (var i = 0; i < _myCardOrder.Count; i++)
        {
            MyCardsContainer.AddChild(MakeDraggableCard(_myCardOrder[i], i));
        }
    }
}
