using System;
using Content.Shared._Rat.Research.TechShare;
using Content.Shared.Lathe;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Rat.Research.TechShare;

[GenerateTypedNameReferences]
public sealed partial class TechShareReceiverWindow : DefaultWindow
{
    public event Action? OnAccept;
    public event Action? OnReject;
    public event Action? OnDisconnect;

    private readonly SharedLatheSystem _latheSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SharedLatheSystem>();

    public TechShareReceiverWindow()
    {
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += _ => OnAccept?.Invoke();
        RejectButton.OnPressed += _ => OnReject?.Invoke();
        DisconnectButton.OnPressed += _ => OnDisconnect?.Invoke();
    }

    private string GetRecipeName(string recipeId)
    {
        return _latheSystem.GetRecipeName(recipeId);
    }

    public void UpdateState(TechShareReceiverBuiState state)
    {
        var isIdle = state.PendingRequester == null && state.ConnectedRequester == null;
        var isPending = state.PendingRequester != null && state.ConnectedRequester == null;
        var isConnected = state.ConnectedRequester != null;

        IdlePanel.Visible = isIdle;
        PendingPanel.Visible = isPending;
        ConnectedPanel.Visible = isConnected;

        if (isIdle)
        {
            StatusLabel.Text = Loc.GetString("techshare-receiver-status-idle");
        }
        else if (isPending)
        {
            StatusLabel.Text = Loc.GetString("techshare-receiver-status-pending");
            PendingLabel.Text = Loc.GetString("techshare-receiver-pending-from", ("name", state.PendingRequesterName ?? "???"));

            PendingModeLabel.Text = state.RentalMode == TechShareRentalMode.Production
                ? Loc.GetString("techshare-rental-mode-production")
                : Loc.GetString("techshare-rental-mode-time");

            if (state.RentalMode == TechShareRentalMode.Time && state.OfferedDurationMinutes is { } dur)
            {
                PendingDurationLabel.Text = Loc.GetString("techshare-receiver-offered-duration", ("minutes", dur));
            }
            else if (state.RentalMode == TechShareRentalMode.Production)
            {
                PendingDurationLabel.Text = "";
            }

            PendingRecipeListContainer.RemoveAllChildren();
            if (state.OfferedRecipes != null)
            {
                foreach (var recipeId in state.OfferedRecipes)
                {
                    var countText = state.RentalMode == TechShareRentalMode.Production && state.RemainingProductionCounts != null
                        ? $" ({state.RemainingProductionCounts.GetValueOrDefault(recipeId, 0)})"
                        : "";
                    PendingRecipeListContainer.AddChild(new Label { Text = $"  - {GetRecipeName(recipeId)}{countText}" });
                }
            }
        }
        else if (isConnected)
        {
            StatusLabel.Text = Loc.GetString("techshare-status-connected");
            ConnectedLabel.Text = Loc.GetString("techshare-connected-to", ("name", state.ConnectedRequesterName ?? "???"));

            ConnectedModeLabel.Text = state.RentalMode == TechShareRentalMode.Production
                ? Loc.GetString("techshare-rental-mode-production")
                : Loc.GetString("techshare-rental-mode-time");

            if (state.RentalMode == TechShareRentalMode.Time && state.TimeRemaining is { } remaining)
            {
                var mins = (int) remaining.TotalMinutes;
                var secs = remaining.Seconds;
                TimerLabel.Text = Loc.GetString("techshare-time-remaining", ("time", $"{mins:D2}:{secs:D2}"));
            }
            else if (state.RentalMode == TechShareRentalMode.Production)
            {
                TimerLabel.Text = "";
            }

            ConnectedRecipeListContainer.RemoveAllChildren();
            if (state.OfferedRecipes != null)
            {
                foreach (var recipeId in state.OfferedRecipes)
                {
                    var countText = state.RentalMode == TechShareRentalMode.Production && state.RemainingProductionCounts != null
                        ? $" ({state.RemainingProductionCounts.GetValueOrDefault(recipeId, 0)})"
                        : "";
                    ConnectedRecipeListContainer.AddChild(new Label { Text = $"  - {GetRecipeName(recipeId)}{countText}" });
                }
            }
        }
    }
}
