using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared._Rat.Research.TechShare;
using Content.Shared.Lathe;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Network;

namespace Content.Client._Rat.Research.TechShare;

[GenerateTypedNameReferences]
public sealed partial class TechShareRequestWindow : DefaultWindow
{
    public event Action<NetEntity, List<string>, TechShareRentalMode, int>? OnSendRequest;
    public event Action? OnCancelRequest;
    public event Action? OnDisconnect;

    private readonly List<(NetEntity Uid, string Name)> _receivers = new();
    private readonly List<string> _allRecipes = new();
    private readonly Dictionary<string, CheckBox> _recipeChecks = new();
    private int _selectedReceiverIndex = -1;
    private readonly SharedLatheSystem _latheSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SharedLatheSystem>();

    public TechShareRequestWindow()
    {
        RobustXamlLoader.Load(this);

        DurationSpinBox.OverrideValue(10);

        ReceiverList.OnItemSelected += args =>
        {
            _selectedReceiverIndex = args.ItemIndex;
            UpdateSendButton();
        };

        RecipeSearchBox.OnTextChanged += args =>
        {
            FilterRecipes(args.Text);
        };

        SelectAllButton.OnPressed += _ =>
        {
            foreach (var cb in _recipeChecks.Values)
                cb.Pressed = true;
            UpdateSendButton();
        };

        DeselectAllButton.OnPressed += _ =>
        {
            foreach (var cb in _recipeChecks.Values)
                cb.Pressed = false;
            UpdateSendButton();
        };

        RentalModeToggle.OnToggled += args =>
        {
            UpdateRentalModeUI(args.Pressed);
        };

        SendRequestButton.OnPressed += _ =>
        {
            if (_selectedReceiverIndex < 0 || _selectedReceiverIndex >= _receivers.Count)
                return;

            var selected = new List<string>();
            foreach (var (id, cb) in _recipeChecks)
            {
                if (cb.Pressed)
                    selected.Add(id);
            }

            if (selected.Count == 0)
                return;

            var mode = RentalModeToggle.Pressed ? TechShareRentalMode.Production : TechShareRentalMode.Time;
            var value = DurationSpinBox.Value;
            OnSendRequest?.Invoke(_receivers[_selectedReceiverIndex].Uid, selected, mode, value);
        };

        CancelButton.OnPressed += _ => OnCancelRequest?.Invoke();
        DisconnectButton.OnPressed += _ => OnDisconnect?.Invoke();
    }

    private string GetRecipeName(string recipeId)
    {
        return _latheSystem.GetRecipeName(recipeId);
    }

    private void UpdateRentalModeUI(bool isProductionMode)
    {
        if (isProductionMode)
        {
            DurationLabel.Text = Loc.GetString("techshare-request-production-count");
            DurationUnitLabel.Text = "";
        }
        else
        {
            DurationLabel.Text = Loc.GetString("techshare-request-duration");
            DurationUnitLabel.Text = Loc.GetString("techshare-request-duration-unit");
        }
    }

    private void FilterRecipes(string searchText)
    {
        RecipeListContainer.RemoveAllChildren();
        var search = searchText.ToLower();

        foreach (var recipeId in _allRecipes)
        {
            var name = GetRecipeName(recipeId).ToLower();
            if (string.IsNullOrEmpty(search) || name.Contains(search))
            {
                if (_recipeChecks.TryGetValue(recipeId, out var cb))
                {
                    var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
                    box.AddChild(cb);
                    RecipeListContainer.AddChild(box);
                }
            }
        }
    }

    private void UpdateSendButton()
    {
        var hasReceiver = _selectedReceiverIndex >= 0 && _selectedReceiverIndex < _receivers.Count;
        var hasRecipes = _recipeChecks.Values.Any(cb => cb.Pressed);
        SendRequestButton.Disabled = !hasReceiver || !hasRecipes;
    }

    public void UpdateState(TechShareRequestBuiState state)
    {
        _receivers.Clear();
        _receivers.AddRange(state.AvailableReceivers);

        var isIdle = state.PendingTarget == null && state.ConnectedReceiver == null;
        var isPending = state.PendingTarget != null && state.ConnectedReceiver == null;
        var isConnected = state.ConnectedReceiver != null;

        IdlePanel.Visible = isIdle;
        PendingPanel.Visible = isPending;
        ConnectedPanel.Visible = isConnected;

        if (isIdle)
        {
            StatusLabel.Text = Loc.GetString("techshare-request-status-idle");
            ReceiverList.Clear();
            foreach (var (_, name) in _receivers)
            {
                ReceiverList.AddItem(name);
            }

            // Update recipe list
            _allRecipes.Clear();
            _allRecipes.AddRange(state.AvailableRecipes);
            RecipeListContainer.RemoveAllChildren();
            _recipeChecks.Clear();
            foreach (var recipeId in state.AvailableRecipes)
            {
                var box = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
                var cb = new CheckBox { Text = GetRecipeName(recipeId) };
                cb.OnToggled += _ => UpdateSendButton();
                box.AddChild(cb);
                RecipeListContainer.AddChild(box);
                _recipeChecks[recipeId] = cb;
            }

            // Update bounds based on mode
            UpdateRentalModeUI(RentalModeToggle.Pressed);
            if (RentalModeToggle.Pressed)
            {
                DurationSpinBox.OverrideValue(Math.Clamp(DurationSpinBox.Value, state.MinProductionCount, state.MaxProductionCount));
            }
            else
            {
                DurationSpinBox.OverrideValue(Math.Clamp(DurationSpinBox.Value, state.MinDurationMinutes, state.MaxDurationMinutes));
            }

            _selectedReceiverIndex = -1;
            UpdateSendButton();
        }
        else if (isPending)
        {
            StatusLabel.Text = Loc.GetString("techshare-request-status-pending");
            PendingLabel.Text = Loc.GetString("techshare-request-pending-label");
        }
        else if (isConnected)
        {
            StatusLabel.Text = Loc.GetString("techshare-status-connected");
            ConnectedLabel.Text = Loc.GetString("techshare-connected-to", ("name", state.ConnectedReceiverName ?? "???"));

            if (state.TimeRemaining is { } remaining)
            {
                var mins = (int) remaining.TotalMinutes;
                var secs = remaining.Seconds;
                TimerLabel.Text = Loc.GetString("techshare-time-remaining", ("time", $"{mins:D2}:{secs:D2}"));
            }
            else
            {
                TimerLabel.Text = Loc.GetString("techshare-time-remaining", ("time", "--:--"));
            }

            // Show shared recipes
            SharedRecipeListContainer.RemoveAllChildren();
            if (state.SharedRecipeIds != null)
            {
                foreach (var recipeId in state.SharedRecipeIds)
                {
                    SharedRecipeListContainer.AddChild(new Label { Text = $"  - {GetRecipeName(recipeId)}" });
                }
            }
        }
    }
}
